remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
logo: /logo.png
title: ./bercon-cli
description: BattlEye RCON CLI and go package
markdown: GFM
github:
  zip_url: https://github.com/WoozyMasta/bercon-cli/zipball/master
  tar_url: https://github.com/WoozyMasta/bercon-cli/tarball/master
  linux: https://github.com/WoozyMasta/bercon-cli/releases/latest/download/bercon-cli-linux-amd64
  darwin: https://github.com/WoozyMasta/bercon-cli/releases/latest/download/bercon-cli-darwin-arm64
  windows: https://github.com/WoozyMasta/bercon-cli/releases/latest/download/bercon-cli-windows-amd64.exe
