name: Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - name:  Run base workflow
        uses: ./.github/workflows/base.yml
        with:
          go-version: '1.23'
